apiVersion: v1
kind: Service
metadata:
  #namespace: hivemr3
  name: timeline
spec:
  type: LoadBalancer
  selector:
    hivemr3_app: timeline
  ports:
  - name: prometheus
    protocol: TCP
    port: {{ .Values.prometheus.httpPort }}
    targetPort: 9090
  - name: grafana
    protocol: TCP
    port: {{ .Values.grafana.httpPort }}
    targetPort: 3000
  externalIPs:
  - {{ .Values.timeline.externalIp }}
