apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name.timeline.secret }}
type: Opaque
data:
  {{- if .Values.timeline.createSecret }}
  {{- (.Files.Glob "key/*").AsSecrets | nindent 2 }}
  {{- end }}
