apiVersion: apps/v1
kind: StatefulSet
metadata:
  #namespace: hivemr3
  name: hivemr3-timeline
spec:
  serviceName: timeline
  replicas: 1
  selector:
    matchLabels:
      hivemr3_hive_source: hivesrc3
      hivemr3_app: timeline
  template:
    metadata:
      #namespace: hivemr3
      name: hivemr3-timeline
      labels:
        hivemr3_hive_source: hivesrc3
        hivemr3_app: timeline
        mr3-pod-role: master-role
    spec:
      restartPolicy: Always
      hostAliases:
      {{- range .Values.hostAliases }}
      - ip: {{ .ip }}
        hostnames: 
        {{- range .hostnames }}
        - {{ . }}
        {{- end }}
      {{- end }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  hivemr3_app: metastore
      {{- if .Values.docker.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.docker.imagePullSecrets }}
      {{- end }}
      containers:
      - image: {{ .Values.docker.image }}
        command:
        - /opt/mr3-run/ats/prometheus.sh
        imagePullPolicy: {{ .Values.docker.imagePullPolicy }}
        name: prometheus
        resources:
          requests:
            cpu: {{ .Values.prometheus.resources.requests.cpu }}
            memory: {{ .Values.prometheus.resources.requests.memory }}
          limits:
            cpu: {{ .Values.prometheus.resources.limits.cpu }}
            memory: {{ .Values.prometheus.resources.limits.memory }}
        ports:
        - containerPort: 9090
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 120
          periodSeconds: 120
        volumeMounts:
        - name: conf-k8s-volume
          mountPath: /opt/mr3-run/ats/conf
          readOnly: true
        {{- if .Values.workDir.use }}
        - name: timeline-work-dir-volume
          mountPath: /opt/mr3-run/ats/prometheus/data
        {{- end }}
      - image: {{ .Values.docker.image }}
        command:
        - /opt/mr3-run/ats/grafana.sh
        imagePullPolicy: {{ .Values.docker.imagePullPolicy }}
        name: grafana
        resources:
          requests:
            cpu: {{ .Values.grafana.resources.requests.cpu }}
            memory: {{ .Values.grafana.resources.requests.memory }}
          limits:
            cpu: {{ .Values.grafana.resources.limits.cpu }}
            memory: {{ .Values.grafana.resources.limits.memory }}
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 120
          periodSeconds: 120
        volumeMounts:
        - name: conf-k8s-volume
          mountPath: /opt/mr3-run/ats/conf
          readOnly: true
        {{- if .Values.workDir.use }}
        - name: timeline-work-dir-volume
          mountPath: /opt/mr3-run/ats/grafana/data
        {{- end }}
      volumes:
      - name: conf-k8s-volume
        configMap:
          name: {{ .Values.name.timeline.configMap }}
      {{- if .Values.workDir.use }}
      - name: timeline-work-dir-volume
        persistentVolumeClaim:
          claimName: {{ .Values.name.persistentVolumeClaim }}
      {{- end }}
