name:
  timeline:
    configMap: hivemr3-timeline-configmap
  persistentVolume: workdir-pv        # must match name.persistentVolume in hive/values.yaml
  persistentVolumeClaim: workdir-pvc  # must match name.persistentVolumeClaim in hive/values.yaml

docker:
  image: mr3project/mr3ui:1.5
  imagePullPolicy: Always
  imagePullSecrets: 

ui:
  httpPort: 19003

prometheus:
  httpPort: 9090
  resources:
    requests:
      cpu: 1.25
      memory: 4096Mi
    limits:
      cpu: 1.25
      memory: 4096Mi

grafana:
  httpPort: 3000
  resources:
    requests:
      cpu: 0.25
      memory: 512Mi
    limits:
      cpu: 0.25
      memory: 512Mi

workDir:
  # true: use PersistentVolumeClaim created for Hive on MR3
  # false: do not use PersistentVolumeClaim
  use: true

hostAliases:
- ip: "1.1.1.1"
  hostnames:
  - "red0"

