apiVersion: v1
kind: Service
metadata:
  namespace: hivemr3
  name: timeline
spec:
  type: LoadBalancer
  selector:
    hivemr3_app: timeline
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: 9090
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
  externalIPs:
  - 1.1.1.1
