apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hivemr3
  name: workdir-pvc
spec:
  storageClassName: "aws-efs"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
