name:
  ranger:
    configMap: hivemr3-ranger-configmap
    secret: hivemr3-ranger-secret
  persistentVolume: workdir-pv        # must match name.persistentVolume in hive/values.yaml
  persistentVolumeClaim: workdir-pvc  # must match name.persistentVolumeClaim in hive/values.yaml

docker:
  image: mr3project/ranger:2.6.0
  user: ranger
  imagePullPolicy: Always
  imagePullSecrets: 

ranger:
  httpPort: 6080
  httpsPort: 6182
  solrPort: 6083
  externalIp: 1.1.1.1

  createSecret: true

  rangerResources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 1
      memory: 4Gi
  solrResources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 1
      memory: 4Gi

workDir:
  # true: use PersistentVolumeClaim created for Hive on MR3
  # false: do not use PersistentVolumeClaim
  use: true
    
logLevel: INFO

hostAliases:
- ip: "1.1.1.1"
  hostnames:
  - "red0"

